enableTensorboard: True #
test_during_training: True #

### database ###

# ### database ###
# LIVE:
#   datainfo: ./data/LIVEfullinfo.mat
#   im_dir: /home/syang/ysdata/QA_dataset/LIVE-IQA/
#   n_distortions: 5

# patch_size: 32
# stride: 32

# train_ratio: 0.6
# # val_ratio: 0.2  #
# test_ratio: 0.2  #

LIVE:
  datainfo: /home/user/Desktop/SGDNet/acmmm_release/data/liveysnew.mat
  im_dir: /home/user/Desktop/SGDNet/IQA_saliencymaps/
  sim_dir:  /home/user/Desktop/SGDNet/IQA_saliencymaps/predictions_DINet_live/
  n_distortions: 5
  train_ratio: 0.78  #23 (6) 6
# val_ratio: 0.2  #
  test_ratio: 0.22  #
  shape_r: 512
  shape_c: 768


#shape_r shape_c  H,W
LIVEc:
  datainfo: /home/user/Desktop/SGDNet/acmmm_release/data/clive1162ysnew.mat
  sim_dir: /home/user/Desktop/SGDNet/IQA_saliencymaps/predictions_DINet_livec/
  im_dir: /home/user/Desktop/SGDNet/IQA_saliencymaps/
#  n_distortions: 5
  train_ratio: 0.8
# val_ratio: 0.2  #
  test_ratio: 0.2  #
  # nb_imgs_train: 698
  # nb_imgs_val: 232
  # nb_imgs_test: 232
  shape_r: 500
  shape_c: 500


TID2013:
  datainfo: /home/user/Desktop/SGDNet/acmmm_release/data/tid2013ysnew.mat
  sim_dir: /home/user/Desktop/SGDNet/IQA_saliencymaps/predictions_DINet_tid2013/
  im_dir: /home/user/Desktop/SGDNet/IQA_saliencymaps/
#  n_distortions: 5
  train_ratio: 0.8
# val_ratio: 0.2  #
  test_ratio: 0.2  #
  shape_r: 384
  shape_c: 512
  # nb_imgs_train: 1800
  # nb_imgs_val: 600
  # nb_imgs_test: 600


CSIQ:
  datainfo: /home/user/Desktop/SGDNet/acmmm_release/data/csiqysnew.mat
  sim_dir: /home/user/Desktop/SGDNet/IQA_saliencymaps/predictions_DINet_csiq/
  im_dir: /home/user/Desktop/SGDNet/IQA_saliencymaps/
#  n_distortions: 5
  train_ratio: 0.8
# val_ratio: 0.2  #
  test_ratio: 0.2  #
  shape_r: 512
  shape_c: 512
  # nb_imgs_train: 1800
  # nb_imgs_val: 600
  # nb_imgs_test: 600    

Koniq10k:
  im_dir: /home/user/Desktop/SGDNet/koniq10k_1024x768/1024x768/
  sim_dir: /home/user/Desktop/SGDNet/IQA_saliencymaps/koniq10k_saliencymaps/predictions_DINet_koniq10k/
  # data_path: ../koniq10k/
  datainfo: /home/user/Desktop/SGDNet/acmmm_release/data/koniq10kysnew.mat
#  patch_size: 32
#  stride: 32
  train_ratio: 0.8014
# val_ratio: 0.2  #
  test_ratio: 0.1986  #
#   train_no: 7073
# # val_ratio: 0.2  #
#   val_no: 1000 
#   test_ratio: 2000  #
#  datainfo: ./data/LIVEfullinfo.mat
#  im_dir: /home/syang/ysdata/QA_dataset/LIVE-IQA/
  shape_r: 384
  shape_c: 512

Koniq10ksam:
  im_dir: /home/user/Desktop/SGDNet/koniq10k_1024x768/1024x768/
  sim_dir: /home/user/Desktop/SGDNet/IQA_saliencymaps/koniq10k_saliencymaps/predictions_sam_koniq10k/
  # data_path: ../koniq10k/
  datainfo: /home/user/Desktop/SGDNet/acmmm_release/data/koniq10kysnew.mat
#  patch_size: 32
#  stride: 32
  train_ratio: 0.8014
# val_ratio: 0.2  #
  test_ratio:  0.1986  #
#   train_no: 7073
# # val_ratio: 0.2  #
#   val_no: 1000 
#   test_ratio: 2000  #
#  datainfo: ./data/LIVEfullinfo.mat
#  im_dir: /home/syang/ysdata/QA_dataset/LIVE-IQA/
  shape_r: 384
  shape_c: 512


Koniq10ksalgan:
  im_dir: /home/user/Desktop/SGDNet/koniq10k_1024x768/1024x768/
  sim_dir: /home/user/Desktop/SGDNet/IQA_saliencymaps/koniq10k_saliencymaps/predictions_salgan_koniq10k/
  # data_path: ../koniq10k/
  datainfo: /home/user/Desktop/SGDNet/acmmm_release/data/koniq10kysnew.mat
#  patch_size: 32
#  stride: 32
  train_ratio: 0.8014
# val_ratio: 0.2  #
  test_ratio: 0.1986  #
#   train_no: 7073
# # val_ratio: 0.2  #
#   val_no: 1000 
#   test_ratio: 2000  #
#  datainfo: ./data/LIVEfullinfo.mat
#  im_dir: /home/syang/ysdata/QA_dataset/LIVE-IQA/
  shape_r: 384
  shape_c: 512

Koniq10kdva:
  im_dir: /home/user/Desktop/SGDNet/koniq10k_1024x768/1024x768/
  sim_dir: /home/user/Desktop/SGDNet/IQA_saliencymaps/koniq10k_saliencymaps/predictions_DVA_koniq10k/
  # data_path: ../koniq10k/
  datainfo: /home/user/Desktop/SGDNet/acmmm_release/data/koniq10kysnew.mat
#  patch_size: 32
#  stride: 32
  train_ratio: 0.8014
# val_ratio: 0.2  #
  test_ratio: 0.1986  #
#   train_no: 7073
# # val_ratio: 0.2  #
#   val_no: 1000 
#   test_ratio: 2000  #
#  datainfo: ./data/LIVEfullinfo.mat
#  im_dir: /home/syang/ysdata/QA_dataset/LIVE-IQA/
  shape_r: 384
  shape_c: 512


#CUDA_VISIBLE_DEVICES=0 python3 main.py  --database=Koniq10k --lr=1e-4 --batch_size=19 --out2dim=1024  --saliency=output --phase=train
